preset: symfony

risky: false

linting: true

enabled:
    - align_equals
    - align_double_arrow
    - short_array_syntax
    - ordered_imports
    - newline_after_open_tag
    - multiline_spaces_before_semicolon
    - no_useless_return
    - phpdoc_order

disabled:
  - unalign_double_arrow
  - unalign_equals